### ISSUE TITLE
Edit slot: slot_type selector not updated based on original slot

### ISSUE THREAD

**Issue by barnagoz** [difcsi/e5vosdosite#305] opened 2023-10-31 17:14 UTC
**Describe the bug**
When opening a "Programsáv" to edit, the form shows it is an "Előadássáv".

**To Reproduce**
1. Go to _/admin/sav_
2. Click on a slot which has "Programsáv" as type

**Expected behavior**
The editing form should show "Programsáv".

**Screenshots**
<img width="1496" alt="1" src="https://github.com/difcsi/e5vosdosite/assets/82385832/bc1839fa-366f-4bd4-bdb3-56d1ecaf1c8a">
<img width="1496" alt="2" src="https://github.com/difcsi/e5vosdosite/assets/82385832/dd50d838-91e7-48c9-b4f6-1d4eb49eab98">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Arc (Chromium)
 - Version: 1.14.0 (42789)

**Comment by difcsi** [comment] 2023-10-31 18:48
This is caused by #275

**Comment by difcsi** [comment] 2023-10-31 18:51
non-priority justification: purely admin inconvenience

**Comment by difcsi** [comment] 2023-11-02 18:35
fixed in: [096994c52ea12564c093fb915ab4e40f8d95f04e](https://github.com/difcsi/e5vosdosite/commit/096994c52ea12564c093fb915ab4e40f8d95f04e)

**Closed by difcsi** 2023-11-02 18:35 UTC
Labels: bug, Frontend, Non-priority
